development:
  adapter: postgresql
  encoding: unicode
  database: digestif_production
  pool: 5
  username: digestif
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>

development:
  adapter: postgresql
  encoding: unicode
  database: digestif_development
  pool: 5
  username: digestif
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: digestif_test
  pool: 5
  username: digestif
  password: password
